server:
  port: 8080
krpano:
  tools-path: D://tool//krpano-1.20.6
  upload-path: D://tools//upload//
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/noi_code?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

